### ISSUE TITLE
Why is ezknitr a new package?

### ISSUE THREAD

**Issue by mattdowle** [daattali/ezknitr#13]
This package looks great!
Is there an insurmountable problem that prevents it being a contribution (pull request) to existing and established `knitr`?

**Comment by daattali** [comment]
To be honest, I don't remember the exact chain of events, but the reason is probably not very strong.

I initially wrote a simple version of this package when I was a complete R noob [here](https://github.com/daattali/rsalad/blob/778772486d9365bd49db76d1dc857c7115d058d7/inst/doc/spinMyR.md) just as a way to make knitting documents easier for myself. It was before I knew how to write packages and make pull requests and before I had any R credibility. Then I met Yihui in person and told him about my problem and solution, and he asked me to open a github issue so that he could look into incorporating it into knitr. [This is that issue](https://github.com/yihui/knitr/issues/943). Eventually I made it into a little package and was too afraid to overstep my boundaries by trying to add it into knitr myself, and after some time Yihui decided to officially drop the issue and just link to this package as an addon.

So, not a great reason, mostly because I was a scared newbie
